# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/triage_mascotas
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernatec
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Nombre de la app
spring.application.name=triage-mascotas


# JWT
jwt.secret=VetTriageSecretKey2026SuperSeguraParaJWT
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method